@apiUrl = http://localhost:5152/

###
POST {{apiUrl}}listBillings
Accept: application/json
Content-Type: application/json

{   
    "StartDate": null,
    "EndDate":null,
    "Amount": null,
    "DeltaAmount": null,
    "Title": null,
    "WithChecked": true
}

###
POST {{apiUrl}}addBilling
Accept: application/json
Content-Type: application/json

{
    "ValuationDate":
    {
        "Day": 6,
        "Month": 1,
        "Year":2025
    },
    "Title": "AAAAA",
    "Amount": 148.52,
    "Checked": false,
    "Comment": "commentaire",
    "IsSaving": true
}

###
POST {{apiUrl}}editBilling
Accept: application/json
Content-Type: application/json

{
    "Id": "22c07430-b4d2-456c-aabc-8b741e49ec08",
    "ValuationDate": null,
    "Title": "Test 2",
    "Amount": 112.11,
    "Checked": true,
    "Comment": null,
    "IsSaving": null
}

###
POST {{apiUrl}}deleteBilling
Accept: application/json
Content-Type: application/json

{
    "Id": "a4f7e6a4-de68-4238-9ddf-a96db7a786ce"
}

###
POST {{apiUrl}}getBilling
Accept: application/json
Content-Type: application/json

{
    "Id": "14fd77b4-b3c4-429c-8f7a-8662a7f50936"
}

###
POST {{apiUrl}}listRepetitiveBillings
Accept: application/json
Content-Type: application/json

{   
}

###
POST {{apiUrl}}addRepetitiveBilling
Accept: application/json
Content-Type: application/json

{
    "NextValuationDate":
    {
        "Day": 15,
        "Month": 2,
        "Year":2025
    },
    "Title": "Répétition 2",
    "Amount": 65.54,
    "IsSaving": true,
    "Frequence": 2
}

###
POST {{apiUrl}}editRepetitiveBilling
Accept: application/json
Content-Type: application/json

{
    "Id": "790d257f-9526-4558-afa0-5a229ddde6c8",
    "NextValuationDate": null,
    "Title": "Répétition éditée 3",
    "Amount": null,
    "IsSaving": null,
    "Frequence": 3
}

###
POST {{apiUrl}}deleteRepetitiveBilling
Accept: application/json
Content-Type: application/json

{
    "Id": "790d257f-9526-4558-afa0-5a229ddde6c8"
}

###
POST {{apiUrl}}getRepetitiveBilling
Accept: application/json
Content-Type: application/json

{
    "Id": "f0a93daa-14cf-41d4-8840-773c9280806b"
}

###
POST {{apiUrl}}getSummary
Accept: application/json
Content-Type: application/json

{   
}

###
POST {{apiUrl}}showProjection
Accept: application/json
Content-Type: application/json

{   
}

###
POST {{apiUrl}}insertNextBilling
Accept: application/json
Content-Type: application/json

{  
    "RepetitiveBillingId": "f0a93daa-14cf-41d4-8840-773c9280806b" 
}

###
POST {{apiUrl}}multipleInsertNextBilling
Accept: application/json
Content-Type: application/json

{  
    "MaxDate": 
    {
        "Day": 15,
        "Month": 7,
        "Year":2025
    }
}

###
POST {{apiUrl}}importFile
Accept: application/json
Content-Type: application/json

{  
    "FilePath": "C:\\Users\\thehe\\Downloads\\CA20250106_101507.ofx"
}

###
POST {{apiUrl}}showImport
Accept: application/json
Content-Type: application/json

{  
}

###
POST {{apiUrl}}showImportLineDetail
Accept: application/json
Content-Type: application/json

{
    "ImportLineId": "7921312045222"
}

###
POST {{apiUrl}}matchBilling
Accept: application/json
Content-Type: application/json

{  
    "ImportLineId": "7921312045222",
    "BillingId": "23b389c2-c7b8-4d4b-a28b-57176c947725"
}

###
POST {{apiUrl}}commitImport
Accept: application/json
Content-Type: application/json

{  
}
