@apiUrl = http://localhost:5152/

###
POST {{apiUrl}}listBillings
Accept: application/json
Content-Type: application/json

{   
    "StartDate": null,
    "EndDate":null,
    "Amount": null,
    "DeltaAmount": null,
    "Title": null,
    "WithChecked": null
}

###
POST {{apiUrl}}addBilling
Accept: application/json
Content-Type: application/json

{
    "ValuationDate":
    {
        "Day": 15,
        "Month": 6,
        "Year":2024
    },
    "Title": "Test 1",
    "Amount": 65.54,
    "Checked": false,
    "Comment": "commentaire",
    "IsSaving": true
}

###
POST {{apiUrl}}editBilling
Accept: application/json
Content-Type: application/json

{
    "Id": "22c07430-b4d2-456c-aabc-8b741e49ec08",
    "ValuationDate": null,
    "Title": "Test 2",
    "Amount": 112.11,
    "Checked": null,
    "Comment": null,
    "IsSaving": null
}