/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddBillingOutput
 */
export interface AddBillingOutput {
    /**
     * 
     * @type {string}
     * @memberof AddBillingOutput
     */
    newId: string;
}

/**
 * Check if a given object implements the AddBillingOutput interface.
 */
export function instanceOfAddBillingOutput(value: object): value is AddBillingOutput {
    if (!('newId' in value) || value['newId'] === undefined) return false;
    return true;
}

export function AddBillingOutputFromJSON(json: any): AddBillingOutput {
    return AddBillingOutputFromJSONTyped(json, false);
}

export function AddBillingOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddBillingOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'newId': json['newId'],
    };
}

export function AddBillingOutputToJSON(value?: AddBillingOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'newId': value['newId'],
    };
}

