/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShortDate } from './ShortDate';
import {
    ShortDateFromJSON,
    ShortDateFromJSONTyped,
    ShortDateToJSON,
} from './ShortDate';
import type { Frequence } from './Frequence';
import {
    FrequenceFromJSON,
    FrequenceFromJSONTyped,
    FrequenceToJSON,
} from './Frequence';

/**
 * 
 * @export
 * @interface AddRepetitiveBillingOutput
 */
export interface AddRepetitiveBillingOutput {
    /**
     * 
     * @type {string}
     * @memberof AddRepetitiveBillingOutput
     */
    id: string;
    /**
     * 
     * @type {ShortDate}
     * @memberof AddRepetitiveBillingOutput
     */
    nextValuationDate: ShortDate;
    /**
     * 
     * @type {string}
     * @memberof AddRepetitiveBillingOutput
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof AddRepetitiveBillingOutput
     */
    amount: number;
    /**
     * 
     * @type {boolean}
     * @memberof AddRepetitiveBillingOutput
     */
    isSaving: boolean;
    /**
     * 
     * @type {Frequence}
     * @memberof AddRepetitiveBillingOutput
     */
    frequence: Frequence;
}



/**
 * Check if a given object implements the AddRepetitiveBillingOutput interface.
 */
export function instanceOfAddRepetitiveBillingOutput(value: object): value is AddRepetitiveBillingOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nextValuationDate' in value) || value['nextValuationDate'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('isSaving' in value) || value['isSaving'] === undefined) return false;
    if (!('frequence' in value) || value['frequence'] === undefined) return false;
    return true;
}

export function AddRepetitiveBillingOutputFromJSON(json: any): AddRepetitiveBillingOutput {
    return AddRepetitiveBillingOutputFromJSONTyped(json, false);
}

export function AddRepetitiveBillingOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddRepetitiveBillingOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nextValuationDate': ShortDateFromJSON(json['nextValuationDate']),
        'title': json['title'],
        'amount': json['amount'],
        'isSaving': json['isSaving'],
        'frequence': FrequenceFromJSON(json['frequence']),
    };
}

export function AddRepetitiveBillingOutputToJSON(value?: AddRepetitiveBillingOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'nextValuationDate': ShortDateToJSON(value['nextValuationDate']),
        'title': value['title'],
        'amount': value['amount'],
        'isSaving': value['isSaving'],
        'frequence': FrequenceToJSON(value['frequence']),
    };
}

