/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBillingOutput
 */
export interface DeleteBillingOutput {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteBillingOutput
     */
    hasBeenDeleted: boolean;
}

/**
 * Check if a given object implements the DeleteBillingOutput interface.
 */
export function instanceOfDeleteBillingOutput(value: object): value is DeleteBillingOutput {
    if (!('hasBeenDeleted' in value) || value['hasBeenDeleted'] === undefined) return false;
    return true;
}

export function DeleteBillingOutputFromJSON(json: any): DeleteBillingOutput {
    return DeleteBillingOutputFromJSONTyped(json, false);
}

export function DeleteBillingOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBillingOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'hasBeenDeleted': json['hasBeenDeleted'],
    };
}

export function DeleteBillingOutputToJSON(value?: DeleteBillingOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hasBeenDeleted': value['hasBeenDeleted'],
    };
}

