/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteRepetitiveBillingInput
 */
export interface DeleteRepetitiveBillingInput {
    /**
     * 
     * @type {string}
     * @memberof DeleteRepetitiveBillingInput
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteRepetitiveBillingInput interface.
 */
export function instanceOfDeleteRepetitiveBillingInput(value: object): value is DeleteRepetitiveBillingInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeleteRepetitiveBillingInputFromJSON(json: any): DeleteRepetitiveBillingInput {
    return DeleteRepetitiveBillingInputFromJSONTyped(json, false);
}

export function DeleteRepetitiveBillingInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRepetitiveBillingInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteRepetitiveBillingInputToJSON(value?: DeleteRepetitiveBillingInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

