/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditBillingOutput
 */
export interface EditBillingOutput {
    /**
     * 
     * @type {boolean}
     * @memberof EditBillingOutput
     */
    hasBeenEdited: boolean;
}

/**
 * Check if a given object implements the EditBillingOutput interface.
 */
export function instanceOfEditBillingOutput(value: object): value is EditBillingOutput {
    if (!('hasBeenEdited' in value) || value['hasBeenEdited'] === undefined) return false;
    return true;
}

export function EditBillingOutputFromJSON(json: any): EditBillingOutput {
    return EditBillingOutputFromJSONTyped(json, false);
}

export function EditBillingOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditBillingOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'hasBeenEdited': json['hasBeenEdited'],
    };
}

export function EditBillingOutputToJSON(value?: EditBillingOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hasBeenEdited': value['hasBeenEdited'],
    };
}

