/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Frequence = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type Frequence = typeof Frequence[keyof typeof Frequence];


export function instanceOfFrequence(value: any): boolean {
    for (const key in Frequence) {
        if (Object.prototype.hasOwnProperty.call(Frequence, key)) {
            if (Frequence[key as keyof typeof Frequence] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FrequenceFromJSON(json: any): Frequence {
    return FrequenceFromJSONTyped(json, false);
}

export function FrequenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Frequence {
    return json as Frequence;
}

export function FrequenceToJSON(value?: Frequence | null): any {
    return value as any;
}

