/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBillingInput
 */
export interface GetBillingInput {
    /**
     * 
     * @type {string}
     * @memberof GetBillingInput
     */
    id: string;
}

/**
 * Check if a given object implements the GetBillingInput interface.
 */
export function instanceOfGetBillingInput(value: object): value is GetBillingInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetBillingInputFromJSON(json: any): GetBillingInput {
    return GetBillingInputFromJSONTyped(json, false);
}

export function GetBillingInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function GetBillingInputToJSON(value?: GetBillingInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

