/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSummaryOutput
 */
export interface GetSummaryOutput {
    /**
     * 
     * @type {number}
     * @memberof GetSummaryOutput
     */
    amount: number;
}

/**
 * Check if a given object implements the GetSummaryOutput interface.
 */
export function instanceOfGetSummaryOutput(value: object): value is GetSummaryOutput {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function GetSummaryOutputFromJSON(json: any): GetSummaryOutput {
    return GetSummaryOutputFromJSONTyped(json, false);
}

export function GetSummaryOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSummaryOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function GetSummaryOutputToJSON(value?: GetSummaryOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
    };
}

