/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSummaryResult
 */
export interface GetSummaryResult {
    /**
     * 
     * @type {number}
     * @memberof GetSummaryResult
     */
    amount: number;
}

/**
 * Check if a given object implements the GetSummaryResult interface.
 */
export function instanceOfGetSummaryResult(value: object): value is GetSummaryResult {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function GetSummaryResultFromJSON(json: any): GetSummaryResult {
    return GetSummaryResultFromJSONTyped(json, false);
}

export function GetSummaryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSummaryResult {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function GetSummaryResultToJSON(value?: GetSummaryResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
    };
}

