/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InsertNextBillingOutputRepetitiveBilling } from './InsertNextBillingOutputRepetitiveBilling';
import {
    InsertNextBillingOutputRepetitiveBillingFromJSON,
    InsertNextBillingOutputRepetitiveBillingFromJSONTyped,
    InsertNextBillingOutputRepetitiveBillingToJSON,
} from './InsertNextBillingOutputRepetitiveBilling';
import type { InsertNextBillingOutputBilling } from './InsertNextBillingOutputBilling';
import {
    InsertNextBillingOutputBillingFromJSON,
    InsertNextBillingOutputBillingFromJSONTyped,
    InsertNextBillingOutputBillingToJSON,
} from './InsertNextBillingOutputBilling';

/**
 * 
 * @export
 * @interface InsertNextBillingOutput
 */
export interface InsertNextBillingOutput {
    /**
     * 
     * @type {InsertNextBillingOutputBilling}
     * @memberof InsertNextBillingOutput
     */
    billing: InsertNextBillingOutputBilling;
    /**
     * 
     * @type {InsertNextBillingOutputRepetitiveBilling}
     * @memberof InsertNextBillingOutput
     */
    repetitiveBilling: InsertNextBillingOutputRepetitiveBilling;
}

/**
 * Check if a given object implements the InsertNextBillingOutput interface.
 */
export function instanceOfInsertNextBillingOutput(value: object): value is InsertNextBillingOutput {
    if (!('billing' in value) || value['billing'] === undefined) return false;
    if (!('repetitiveBilling' in value) || value['repetitiveBilling'] === undefined) return false;
    return true;
}

export function InsertNextBillingOutputFromJSON(json: any): InsertNextBillingOutput {
    return InsertNextBillingOutputFromJSONTyped(json, false);
}

export function InsertNextBillingOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsertNextBillingOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'billing': InsertNextBillingOutputBillingFromJSON(json['billing']),
        'repetitiveBilling': InsertNextBillingOutputRepetitiveBillingFromJSON(json['repetitiveBilling']),
    };
}

export function InsertNextBillingOutputToJSON(value?: InsertNextBillingOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'billing': InsertNextBillingOutputBillingToJSON(value['billing']),
        'repetitiveBilling': InsertNextBillingOutputRepetitiveBillingToJSON(value['repetitiveBilling']),
    };
}

