/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InsertNextBillingInput
 */
export interface InsertNextBillingInput {
    /**
     * 
     * @type {string}
     * @memberof InsertNextBillingInput
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof InsertNextBillingInput
     */
    incrementNextValuationDate: boolean;
}

/**
 * Check if a given object implements the InsertNextBillingInput interface.
 */
export function instanceOfInsertNextBillingInput(value: object): value is InsertNextBillingInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incrementNextValuationDate' in value) || value['incrementNextValuationDate'] === undefined) return false;
    return true;
}

export function InsertNextBillingInputFromJSON(json: any): InsertNextBillingInput {
    return InsertNextBillingInputFromJSONTyped(json, false);
}

export function InsertNextBillingInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsertNextBillingInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'incrementNextValuationDate': json['incrementNextValuationDate'],
    };
}

export function InsertNextBillingInputToJSON(value?: InsertNextBillingInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'incrementNextValuationDate': value['incrementNextValuationDate'],
    };
}

