/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBillingsInput
 */
export interface ListBillingsInput {
    /**
     * 
     * @type {string}
     * @memberof ListBillingsInput
     */
    title?: string | null;
}

/**
 * Check if a given object implements the ListBillingsInput interface.
 */
export function instanceOfListBillingsInput(value: object): value is ListBillingsInput {
    return true;
}

export function ListBillingsInputFromJSON(json: any): ListBillingsInput {
    return ListBillingsInputFromJSONTyped(json, false);
}

export function ListBillingsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBillingsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ListBillingsInputToJSON(value?: ListBillingsInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
    };
}

