/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtosShortDate } from './DtosShortDate';
import {
    DtosShortDateFromJSON,
    DtosShortDateFromJSONTyped,
    DtosShortDateToJSON,
} from './DtosShortDate';

/**
 * 
 * @export
 * @interface ListBillingsOutput
 */
export interface ListBillingsOutput {
    /**
     * 
     * @type {string}
     * @memberof ListBillingsOutput
     */
    id: string;
    /**
     * 
     * @type {DtosShortDate}
     * @memberof ListBillingsOutput
     */
    valuationDate: DtosShortDate;
    /**
     * 
     * @type {string}
     * @memberof ListBillingsOutput
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ListBillingsOutput
     */
    amount: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListBillingsOutput
     */
    checked: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListBillingsOutput
     */
    comment?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ListBillingsOutput
     */
    isArchived: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListBillingsOutput
     */
    isSaving: boolean;
}

/**
 * Check if a given object implements the ListBillingsOutput interface.
 */
export function instanceOfListBillingsOutput(value: object): value is ListBillingsOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('valuationDate' in value) || value['valuationDate'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('checked' in value) || value['checked'] === undefined) return false;
    if (!('isArchived' in value) || value['isArchived'] === undefined) return false;
    if (!('isSaving' in value) || value['isSaving'] === undefined) return false;
    return true;
}

export function ListBillingsOutputFromJSON(json: any): ListBillingsOutput {
    return ListBillingsOutputFromJSONTyped(json, false);
}

export function ListBillingsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBillingsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'valuationDate': DtosShortDateFromJSON(json['valuationDate']),
        'title': json['title'],
        'amount': json['amount'],
        'checked': json['checked'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'isArchived': json['isArchived'],
        'isSaving': json['isSaving'],
    };
}

export function ListBillingsOutputToJSON(value?: ListBillingsOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'valuationDate': DtosShortDateToJSON(value['valuationDate']),
        'title': value['title'],
        'amount': value['amount'],
        'checked': value['checked'],
        'comment': value['comment'],
        'isArchived': value['isArchived'],
        'isSaving': value['isSaving'],
    };
}

