/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetCheckedInput
 */
export interface SetCheckedInput {
    /**
     * 
     * @type {string}
     * @memberof SetCheckedInput
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof SetCheckedInput
     */
    checked: boolean;
}

/**
 * Check if a given object implements the SetCheckedInput interface.
 */
export function instanceOfSetCheckedInput(value: object): value is SetCheckedInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('checked' in value) || value['checked'] === undefined) return false;
    return true;
}

export function SetCheckedInputFromJSON(json: any): SetCheckedInput {
    return SetCheckedInputFromJSONTyped(json, false);
}

export function SetCheckedInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCheckedInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'checked': json['checked'],
    };
}

export function SetCheckedInputToJSON(value?: SetCheckedInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'checked': value['checked'],
    };
}

