/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateOnly } from './DateOnly';
import {
    DateOnlyFromJSON,
    DateOnlyFromJSONTyped,
    DateOnlyToJSON,
} from './DateOnly';

/**
 * 
 * @export
 * @interface WeatherForecast
 */
export interface WeatherForecast {
    /**
     * 
     * @type {DateOnly}
     * @memberof WeatherForecast
     */
    date?: DateOnly;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecast
     */
    temperatureC?: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecast
     */
    summary?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecast
     */
    readonly temperatureF?: number;
}

/**
 * Check if a given object implements the WeatherForecast interface.
 */
export function instanceOfWeatherForecast(value: object): value is WeatherForecast {
    return true;
}

export function WeatherForecastFromJSON(json: any): WeatherForecast {
    return WeatherForecastFromJSONTyped(json, false);
}

export function WeatherForecastFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherForecast {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : DateOnlyFromJSON(json['date']),
        'temperatureC': json['temperatureC'] == null ? undefined : json['temperatureC'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'temperatureF': json['temperatureF'] == null ? undefined : json['temperatureF'],
    };
}

export function WeatherForecastToJSON(value?: Omit<WeatherForecast, 'temperatureF'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': DateOnlyToJSON(value['date']),
        'temperatureC': value['temperatureC'],
        'summary': value['summary'],
    };
}

