/* tslint:disable */
/* eslint-disable */
/**
 * LegendaryGuacamole.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddBillingInput,
  AddBillingOutput,
  DeleteBillingInput,
  EditBillingInput,
  EditBillingOutput,
  GetBillingInput,
  GetBillingOutput,
  GetSummaryOutput,
  ListBillingsInput,
  ListBillingsOutput,
  SetCheckedInput,
  SetCheckedOutput,
} from '../models/index';
import {
    AddBillingInputFromJSON,
    AddBillingInputToJSON,
    AddBillingOutputFromJSON,
    AddBillingOutputToJSON,
    DeleteBillingInputFromJSON,
    DeleteBillingInputToJSON,
    EditBillingInputFromJSON,
    EditBillingInputToJSON,
    EditBillingOutputFromJSON,
    EditBillingOutputToJSON,
    GetBillingInputFromJSON,
    GetBillingInputToJSON,
    GetBillingOutputFromJSON,
    GetBillingOutputToJSON,
    GetSummaryOutputFromJSON,
    GetSummaryOutputToJSON,
    ListBillingsInputFromJSON,
    ListBillingsInputToJSON,
    ListBillingsOutputFromJSON,
    ListBillingsOutputToJSON,
    SetCheckedInputFromJSON,
    SetCheckedInputToJSON,
    SetCheckedOutputFromJSON,
    SetCheckedOutputToJSON,
} from '../models/index';

export interface AddBillingRequest {
    addBillingInput: AddBillingInput;
}

export interface DeleteBillingRequest {
    deleteBillingInput: DeleteBillingInput;
}

export interface EditBillingRequest {
    editBillingInput: EditBillingInput;
}

export interface GetBillingRequest {
    getBillingInput: GetBillingInput;
}

export interface GetSummaryRequest {
    body: object;
}

export interface ListBillingsRequest {
    listBillingsInput: ListBillingsInput;
}

export interface SetCheckedRequest {
    setCheckedInput: SetCheckedInput;
}

/**
 * 
 */
export class WorkspaceApi extends runtime.BaseAPI {

    /**
     */
    async addBillingRaw(requestParameters: AddBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddBillingOutput>> {
        if (requestParameters['addBillingInput'] == null) {
            throw new runtime.RequiredError(
                'addBillingInput',
                'Required parameter "addBillingInput" was null or undefined when calling addBilling().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/addBilling`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddBillingInputToJSON(requestParameters['addBillingInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddBillingOutputFromJSON(jsonValue));
    }

    /**
     */
    async addBilling(addBillingInput: AddBillingInput, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddBillingOutput> {
        const response = await this.addBillingRaw({ addBillingInput: addBillingInput }, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteBillingRaw(requestParameters: DeleteBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['deleteBillingInput'] == null) {
            throw new runtime.RequiredError(
                'deleteBillingInput',
                'Required parameter "deleteBillingInput" was null or undefined when calling deleteBilling().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/deleteBilling`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteBillingInputToJSON(requestParameters['deleteBillingInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async deleteBilling(deleteBillingInput: DeleteBillingInput, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteBillingRaw({ deleteBillingInput: deleteBillingInput }, initOverrides);
        return await response.value();
    }

    /**
     */
    async editBillingRaw(requestParameters: EditBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EditBillingOutput>> {
        if (requestParameters['editBillingInput'] == null) {
            throw new runtime.RequiredError(
                'editBillingInput',
                'Required parameter "editBillingInput" was null or undefined when calling editBilling().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/editBilling`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EditBillingInputToJSON(requestParameters['editBillingInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EditBillingOutputFromJSON(jsonValue));
    }

    /**
     */
    async editBilling(editBillingInput: EditBillingInput, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EditBillingOutput> {
        const response = await this.editBillingRaw({ editBillingInput: editBillingInput }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBillingRaw(requestParameters: GetBillingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBillingOutput>> {
        if (requestParameters['getBillingInput'] == null) {
            throw new runtime.RequiredError(
                'getBillingInput',
                'Required parameter "getBillingInput" was null or undefined when calling getBilling().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/getBilling`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetBillingInputToJSON(requestParameters['getBillingInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBillingOutputFromJSON(jsonValue));
    }

    /**
     */
    async getBilling(getBillingInput: GetBillingInput, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBillingOutput> {
        const response = await this.getBillingRaw({ getBillingInput: getBillingInput }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSummaryRaw(requestParameters: GetSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSummaryOutput>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling getSummary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/getSummary`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSummaryOutputFromJSON(jsonValue));
    }

    /**
     */
    async getSummary(body: object, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSummaryOutput> {
        const response = await this.getSummaryRaw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     */
    async listBillingsRaw(requestParameters: ListBillingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListBillingsOutput>>> {
        if (requestParameters['listBillingsInput'] == null) {
            throw new runtime.RequiredError(
                'listBillingsInput',
                'Required parameter "listBillingsInput" was null or undefined when calling listBillings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/listBillings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListBillingsInputToJSON(requestParameters['listBillingsInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListBillingsOutputFromJSON));
    }

    /**
     */
    async listBillings(listBillingsInput: ListBillingsInput, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListBillingsOutput>> {
        const response = await this.listBillingsRaw({ listBillingsInput: listBillingsInput }, initOverrides);
        return await response.value();
    }

    /**
     */
    async setCheckedRaw(requestParameters: SetCheckedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetCheckedOutput>> {
        if (requestParameters['setCheckedInput'] == null) {
            throw new runtime.RequiredError(
                'setCheckedInput',
                'Required parameter "setCheckedInput" was null or undefined when calling setChecked().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/setChecked`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetCheckedInputToJSON(requestParameters['setCheckedInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetCheckedOutputFromJSON(jsonValue));
    }

    /**
     */
    async setChecked(setCheckedInput: SetCheckedInput, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetCheckedOutput> {
        const response = await this.setCheckedRaw({ setCheckedInput: setCheckedInput }, initOverrides);
        return await response.value();
    }

}
